
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/proj-organic-tianle-github-app
owner: ucsb-cs156-s24
repo_name: proj-organic-tianle-github-app
pull_requests: [{"author":{"id":"MDQ6VXNlcjQzNzgzODc3","is_bot":false,"login":"yuxiaolejs","name":"Unics Yu"},"headRefName":"Tianle-GHA-com.tianleyu.github","number":3,"title":"Tianle gha com.tianleyu.GitHub","url":"https://github.com/ucsb-cs156-s24/proj-organic-tianle-github-app/pull/3"},{"author":{"id":"MDQ6VXNlcjExMTkwMTc=","is_bot":false,"login":"pconrad","name":"Phill Conrad"},"headRefName":"Tianle-deployScript","number":2,"title":"Tianle deploy script","url":"https://github.com/ucsb-cs156-s24/proj-organic-tianle-github-app/pull/2"}]
